### ISSUE TITLE
to_pandas float bug

### ISSUE THREAD

**Issue by vojtechmusilek** [rick-jennings/phable#6]
phable: 0.1.13a1
exception: 'float' object has no attribute 'unit'
how to replicate:

```py
from phable.client import Client
with Client(uri, username, password) as client:
  res = client.eval('[{ts: now(), val: 0}, {ts: now()+1s}].toGrid.addMeta({id: @test})')
  df = res.to_pandas()
```

simmiliar to #5 but this time there is no val in second row.
this can happen when reading history of multiple points, in this example there is just single col to make it simple.

**Comment by rick-jennings** [comment]
Thanks for reporting the bug.

I made a new commit to address this:
https://github.com/rick-jennings/phable/commit/0facaa08aadceef848102fe32786bfc14ffbe2af

Would you please review the code changes in this commit and provide your feedback?

FYI.  These changes are in v0.1.13 which was just released on PyPI.

**Comment by vojtechmusilek** [comment]
Looks good, thanks for quick fix
