### ISSUE TITLE
client close err

### ISSUE THREAD

**Issue by showfuture** [rick-jennings/phable#8]
```
def open_hc(self):
        with self.client as hc:
            about = hc.about()
            print(about)
```

After reading the information using the phable package, when attempting to close the client connection using client.close() within the with block in the open_hc function, I encountered an error: 'phable.http.IncorrectHttpResponseStatus: Expected status 200 and received status 404.' when I use self.client.open()， it‘s success， and self.client.close() is fault.  What could be the reason for this?

**Comment by rick-jennings** [comment]
Hi,

The purpose of the context manager, or with statement, is to open and close the session with the Haystack server without requiring the use of the `open` and `close` method on the class `Client`.

Here is an example of how to use the Client's context manager:
https://github.com/rick-jennings/phable?tab=readme-ov-file#example-haystacks-read--hisread-ops

Here is another example of how to use `Client` without a context manager:
https://github.com/rick-jennings/phable?tab=readme-ov-file#example-async-usage-without-context-manager

Ultimately, it is important to remember to close the session with the Haystack server when you are finished making requests to the server.

**Comment by showfuture** [comment]
It seems you may have misunderstood my question. My concern is why I'm encountering a 404 error when using with or the close method of the Client. Could you please help me with that?

```
Traceback (most recent call last):
  File "/root/code/siemens-edge/src/subsystem.py", line 118, in <module>
    optic.open_hc()
  File "/root/code/siemens-edge/src/subsystem.py", line 104, in open_hc
    with self.client as hc:
  File "/root/.local/share/virtualenvs/siemens-edge-i-9CWoel/lib/python3.12/site-packages/phable/client.py", line 98, in __exit__
    self.close()
  File "/root/.local/share/virtualenvs/siemens-edge-i-9CWoel/lib/python3.12/site-packages/phable/client.py", line 110, in close
    call_result = self._call("close")
                  ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/siemens-edge-i-9CWoel/lib/python3.12/site-packages/phable/client.py", line 262, in _call
    response = post(
               ^^^^^
  File "/root/.local/share/virtualenvs/siemens-edge-i-9CWoel/lib/python3.12/site-packages/phable/http.py", line 53, in post
    raise IncorrectHttpResponseStatus(
phable.http.IncorrectHttpResponseStatus: Expected status 200 and received status 404.
```

**Comment by rick-jennings** [comment]
Hi,

Sorry, I may have misread your initial code.  I will reopen this issue.  

We will need to troubleshoot what is going on.  

What is the Haystack server that you are using?  Would you please share with me more code?  

It looks like you are using a class method and I would like to better understand how the object is initialized and state it has.

Once I better understand the problem I might be able to send you some code to use for us to collect more information to help solve a potential problem.

FYI, I am traveling for the next few days and my next response may be delayed.

**Comment by showfuture** [comment]
```
class OpticManager:
    
    def __init__(self) -> None:
        self.url = f'{SIEMENS_HOST}/api/{SIEMENS_PROJECT_NAME}'
        self.client = Client(self.url, SIEMENS_USER_NAME, SIEMENS_PASSWORD)

    def open_hc(self):
        with self.client as hc:
            about = hc.about()
            print(about)

```
![image](https://github.com/rick-jennings/phable/assets/28568478/01d30dec-3c64-4254-96de-ae3ea9e8a290)

I wrote my code based on the example you provided.

**Comment by rick-jennings** [comment]
I think your code should probably work.  As you seem to notice the problem seems to be with the close op.  

As an interim solution you might be able to manually open the session and use the _call method to close the session based on the Haystack server docs.  

The _call method is not part of the public API, so if you get something working please let me know.  I would like to improve the public API.

I will be able to look into the code more in a few days.

**Comment by showfuture** [comment]
```
def to_close(self):
        self.client.open()
        about = self.client.about()
        print(about)
        self.client._call('close')
```
when I use this code. same error:
![image](https://github.com/rick-jennings/phable/assets/28568478/b8c5aaad-0a3d-4c4f-8d7a-d45e0345019c)

**Comment by showfuture** [comment]
> Hi,
> 
> The close op was recently added to Project Haystack's API. The proposal to add it is discussed here: https://project-haystack.org/forum/topic/968
> 
> I suspect the Haystack server that you are using does not support the close op, which is why you see the 404 error in the HTTP response.
> 
> There are several solutions you might want to explore if your Haystack server does not support the close op:
> 
> 1. Reuse the Haystack session.  Once the server closes the session, create a new session.
> 2. Implement the equivalent to the close op using the Haystack server's unique requirements.
> 
> Please let me know if this makes sense and if you need any sample code for the proposed solution 1.

I understand your explanation. My colleague encountered the close failure error using the Java SDK, but after downgrading the version, the error disappeared. Even though I used an older version of the Python SDK, I still encountered this error. My concern is, if my Haystack server does not support the close operation and I cannot close the session, will it result in too many connections and cause other impacts on the server? Regarding your proposed solution 1 code, I would like to receive it. Thank you.

**Comment by rick-jennings** [comment]
Hi, 

I think the best solution would be to see how your specific Haystack server might support the equivalent to the close op. 

Here is an example of how to reuse an auth token between two `Client` instances.  This is not part of the public API, so I would advise you to use this at your own risk and not use it for a long term solution.

```python
from phable.client import Client

# define these settings specific to your use case
uri = "http://localhost:8080/api/demo"
username = "<username"
password = "<password>"


client1 = Client(uri, username, password)

client1.open()
print(client1.about())
print()

auth_token = client1._auth_token

client2 = Client(uri, username, password)
client2._auth_token = auth_token
print(client2.about())
print()
```

We could consider adding similar support to the public API.  

Please be aware the batch hisRead and hisWrite operations were recently added to the Project Haystack API.  I would suggest you to use the hisRead or hisWrite ops for only one point at a time using the standard Haystack ops.

Here is an example of how to do a hisWrite on a single point:
https://github.com/rick-jennings/phable/blob/main/tests/test_client.py#L289

In a future Phable version I would like to make it easier to do a hisWrite.  

I would appreciate feedback on how we could improve Phable.

Note to future readers:  the above referenced URL may not work in the future as expected.

**Comment by rick-jennings** [comment]
Also, please note the `eval` op in the hisWrite example I provided is specific to the SkySpark API.  Please only consider how `Client.his_write()` and it's input `Grid` is applied in that example.

We will work on improving the docs in the future too.

**Comment by showfuture** [comment]
I now want to directly modify the data value of a point instead of modifying the historical data value of a point. Taking C# as an example, the corresponding API is var writeOps = client.PointWriteAsync(new HaystackReference("p:cccg:r:2aa57c0e-8f2b2db2"), 16, "su11", new HaystackNumber(620), null); What is the equivalent API in the Python SDK?

**Comment by showfuture** [comment]
> Phable does not support Project Haystack's `PointWrite` op today.
> 
> I can look into adding `PointWrite` op support in the next release.
> 
> Would you please confirm the `PointWrite` op described in the link below is the feature you are seeking?
> 
> https://project-haystack.org/doc/docHaystack/Ops#pointWrite

 Yes, that's exactly what I need.

**Comment by showfuture** [comment]
> I just created a branch to implement this feature: https://github.com/rick-jennings/phable/tree/add_PointWrite_support
> 
> If you want to start using PointWrite now you could try out Phable version 0.1.14a2 on PyPI: https://pypi.org/project/phable/0.1.14a2/
> 
> In the Git commit [c9acce3](https://github.com/rick-jennings/phable/commit/c9acce3c54839b4b9b4a545c03f816c137a2f3f3) you will see the methods added to `Client` and some tests you can use as examples.
> 
> Please let me know how this works out for you.

yes， it works  for me

**Comment by rick-jennings** [comment]
Hi, showfuture thanks again for the feedback.  I made improvements based on our discussion in Phable version 0.1.14.  

I am still considering how we might be able to have better support in Phable for Haystack servers that do not support the close op.  The challenge I think is keeping the API simple for users who are working with the latest Haystack servers that support the close op.

I would welcome ideas from anyone on this.

**Comment by rick-jennings** [comment]
After further review, I have decided not to make additional changes to support servers that do not support the close op.

When necessary I would suggest others write their own custom code to close the session with the Project Haystack server (that does not support the close op).

Another solution might be updating the software on the server to a newer version that supports the Project Haystack defined close op, which is compatible with Phable's Client.
