### ISSUE TITLE
Can I roll up using Haystack HisRead ops?

### ISSUE THREAD

**Issue by dexkluu** [rick-jennings/phable#9]
In SkySpark ops I can use hisRollup off of a hisRead but it seems like the his_read method using the Client and Haystack ops doesn't have an argument for rolling up the data. I would just use the SkySpark method but I noticed the Haystack ops works better when I want to pull a large date range because the SkySpark ops way limits you to 50k rows while Haystack doesn't seem to limit you. Thanks in advance for the clarification!

**Comment by rick-jennings** [comment]
Hi, 

You might consider asking a question on the SkyFoundry forum about the 50k limit you are seeing.  There could be value having some limit like this in place and using mini batches.

Phable does not support rollup of history data retrieved from the Haystack server today.  We might consider adding this feature in the future.

Rick

**Comment by rick-jennings** [comment]
Also, please take a look at Client.eval() in client.py in case you have not already.
